export const FETCHING_DATA_START = 'FETCHING_DATA_START'
export const CLEAR_DETAILS = 'CLEAR_DETAILS'
export const FETCHING_DATA_SUCCES = 'FETCHING_DATA_SUCCES'
export const FETCHING_DATA_FAILED = 'FETCHING_DATA_FAILED'
export const READMORE_CLICKED = 'READMORE_CLICKED'

export const ADDED_TO_FAVOURITES = 'ADDED_TO_FAVOURITES'

